### PR TITLE
add png24 & png48 in 4 colors

### PR DESCRIPTION
**Pull request by jeffvg**
#### Changes proposed in this Pull Request:
- Convert svg files to 24dp and 48dp png
- png's in blue500, black500, gray500 and white50

#### Screenshots:

image

### CODE REVIEW

**Review by joebochill — COMMENTED** [review]
Looks like we may have missed one of the paths on the Bearing icon:
image

I don't think the Eaton TwoTone icons should change at all (we should either have only one or make them all the same blue/black combo — thoughts @huayunh?)

The rest of them look good.


Can we get one top level folder (`/png`) that has the 48dp and 24dp folder underneath that?

**Comment by huayunh** [comment]
Correct — that Eaton Two Tone icon is the only one we don't want any extra colors on it.

**Comment by jeffvg** [comment]
do we want to keep the original png folder with the scaled png's

**Comment by huayunh** [comment]
I vote for just the 24dp and 48dp pngs

**Comment by huayunh** [comment]
Remember to write some instructions about how you generated those pngs

**Comment by joebochill** [comment]
Looks great Jeff. Just saw one issue with the Eaton Tagline (white): the subtitle is still gray (should be white):
image

**Comment by jeffvg** [comment]
> Looks great Jeff. Just saw one issue with the Eaton Tagline (white): the subtitle is still gray (should be white):
> image

All the tagline icons should be gray and all the two-tone icons should have changing tagline color...

eaton_tagline_white50_48dp 
eaton_two_tone_white50_48dp

**Comment by joebochill** [comment]
The **Eaton Tagline** icons should be:
- Blue Eaton with Blue Tagline (_blue_)
- Black Eaton with Black Tagline (_black_)
- Gray Eaton with Gray Tagline (_gray_)
- White Eaton with White Tagline (_white_)

The **Eaton Two Tone** icons should be:
- Blue Eaton with Blue Tagline (_blue_)
- Blue Eaton with Black Tagline (_black_)
- Blue Eaton with Gray Tagline (_gray_)
- Blue Eaton with White Tagline (_white_)

**Comment by jeffvg** [comment]
Looking at the designer's read me file and the Icon Approval section.
Do we need to require all new svg icons to be converted in to png's (in all four colors) and placed in correct locations for PR approval?

**Comment by joebochill** [comment]
> Looking at the designer's read me file and the Icon Approval section.
> Do we need to require all new svg icons to be converted in to png's (in all four colors) and placed in correct locations for PR approval?

Yes, we should add a note about that

**Review by joebochill — APPROVED** [review]

**Pull request merged**
