### PR TITLE
Add icons; test auto publishing and new typeface update

### PR DESCRIPTION
**Pull request by huayunh**
#### Changes proposed in this Pull Request:
- #105
- #106
- #107
- #109

### CODE REVIEW

**Review by joebochill — APPROVED** [review]
Let's try it!

**Comment by huayunh** [comment]
Get a quick fix in #109

**Comment by jeffvg** [comment]
since this is going to master and publishing, do we need the change log updated?
* v1.2.0 (not published yet)

**Comment by joebochill** [comment]
Yes @huayunh we need to update that

**Comment by huayunh** [comment]
Abuse your adminship

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
