### PR TITLE
Feature/react progress background color

### LINKED ISSUE #75: Add a prop for white backgrounds in progressive icons
#### Describe the desired behavior

image
Progressive icons are sometimes used in dark backgrounds, and our current designs (2 and 4 in the screenshot) might not be favorable in those situations. 

The users should have the ability to either
(1) override styles, or 
(2) a background prop

#### Current behavior

As described above

### PR DESCRIPTION
**Pull request by huayunh**
Fixes #75 

#### Changes proposed in this Pull Request:
- Add `backgroundColor` prop to react progress icons as part of v2.1.0

#### Screenshots:
outlined=false
image

outlined = true
image

### CODE REVIEW

**Comment by huayunh** [comment]
When this get merged in, we should be ready to publish new packages for progress icons

**Review by joebochill — COMMENTED** [review]
There is a slight discrepancy between the battery fill for Angular vs. React:
image
React is still using white for the charging indicator

**Comment by huayunh** [comment]
Ah, I probably need to match Angular to React. I tried at 50%, and it looks... weird.

image

**Comment by joebochill** [comment]
Yeah this looks good

**Review by joebochill — APPROVED** [review]

**Pull request merged**
