### PR TITLE
Feature/pxb 1.8.0

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Includes new icons for the wifi-wiring team.

#### To Test:
- `yarn start`

### CODE REVIEW

**Comment by jeffvg** [comment]
should updated sprites be committed too? (yarn sprites)

**Comment by jeffvg** [comment]
Is this to be tagged as @pxblue with Brightlayer in meta?

**Comment by jeffvg** [comment]
> > Is this to be tagged as @pxblue with Brightlayer in meta?
> 
> No this should be a @pxblue only package; it should not include references to brightlayer ui.

ok we have Brightlayer UI in meta.json and in the svg index

**Comment by emclaug2** [comment]
> ok we have Brightlayer UI in meta.json and in the svg index

Good catch, these refs should be removed now.

**Comment by jeffvg** [comment]
> > ok we have Brightlayer UI in meta.json and in the svg index
> 
> Good catch, these refs should be removed now.

since the meta file has been updated, you might need to commit new sprites but not sure

**Comment by emclaug2** [comment]
@jeffvg I've added the new sprites after changing the metadata.

**Review by jeffvg — APPROVED** [review]
looks good

**Review by huayunh — COMMENTED** [review]
Somehow when I ran `yarn start`, it generated & updated 55 files in the SVG folder. Otherwise this looks pretty good.

image

**Comment by emclaug2** [comment]
> Somehow when I ran `yarn start`, it generated & updated 55 files in the SVG folder. Otherwise this looks pretty good.

I just ran `yarn start` one last time on my mac and pushed out the new files.

**Review by huayunh — APPROVED** [review]

**Pull request merged**
