### PR TITLE
Move color to dependencies

### LINKED ISSUE #96: Color should be a dependency, not peer dependency
#### Describe the bug
Angular progress icons have `color` listed as a peerDependency. 

#### What is the expected behavior?
It should be a regular dependency.

#### Screenshots or links to minimum reproduction example
image

#### Anything else to add?
This is causing an issue when importing a project into stackblitz (color package is not installed). We can manually add the package to the demo, but the core issue is that it should be installed automatically by the progress-icons package.

### PR DESCRIPTION
**Pull request by joebochill**
Fixes #96 .

#### Changes proposed in this Pull Request:
- Move color from peerDependencies to dependencies so it will be automatically installed

### CODE REVIEW

**Comment by jeffvg** [comment]
I ran the build all from root...seeing this

Building entry point '@pxblue/ng-progress-icons'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
**WARNING: No name was provided for external module 'color' in output.globals – guessing 'color'**
Minifying UMD bundle
Copying declaration files
Writing package metadata
Removing scripts section in package.json as it's considered a potential security vulnerability.
Built @pxblue/ng-progress-icons

**Comment by huayunh** [comment]
Remember to update the ng theme showcase too when this gets published

**Comment by jeffvg** [comment]
for the react progress demo, why isn't center available here....

image

**Comment by joebochill** [comment]
> for the react progress demo, why isn't center available here....

You are just typing a string into a div there. It's not tied to a type definition or prop at all. I'm surprised you're getting any suggestions.

If you start typing for the `labelPosition` prop on the actual icon component, it should show you all the options.

**Comment by huayunh** [comment]
Yeah looks like it is just hinting you the options defined on line 4 / line 5 in that file.

**Review by jeffvg — APPROVED** [review]
verified peer dependency color moved. Build all no longer throwing warning

**Pull request merged**
