### PR TITLE
Update dependencies to support react 17

### LINKED ISSUE #111: Update peer dependencies for React progress icons
#### Describe the desired behavior
Update peer dependencies to allow for React 17 and React Dom 17

#### Describe the current behavior
Limited to React 16

#### Is this request related to a current issue?
No

### PR DESCRIPTION
**Pull request by joebochill**
Fixes #111 

#### Changes proposed in this Pull Request:
- Update peer dependencies to support react 17

### CODE REVIEW

**Comment by huayunh** [comment]
Can you do an updated version of progress/react/demo/package.json? I tried to bump things up and use react 17, but couldn't sort out the proper dependency tree

**Comment by huayunh** [comment]
The current project itself spins all good.

**Comment by jeffvg** [comment]
seems good. should we update angular demo package.json to reflect latest for "@pxblue/ng-progress-icons": "^1.1.4" to 1.2.X

**Comment by joebochill** [comment]
> seems good. should we update angular demo package.json to reflect latest for "@pxblue/ng-progress-icons": "^1.1.4" to 1.2.X

This PR is not doing anything with Angular. I logged a new issue #115 to update the Angular demo.

**Comment by huayunh** [comment]
Looks like the CI is not checking the react progress icon demo... I got this when I try to yarn start:react locally:

```shell
./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js
Error: [BABEL] /Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js: Cannot find module 'levenary'
Require stack:
- /Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/babel-preset-react-app/node_modules/@babel/helper-compilation-targets/lib/index.js
- /Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/debug.js
- /Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/index.js
- /Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/babel-preset-react-app/dependencies.js
- /Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/react-scripts/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/react-scripts/node_modules/@babel/core/lib/config/files/index.js
- /Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/react-scripts/node_modules/@babel/core/lib/index.js
- /Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/react-scripts/node_modules/babel-loader/lib/index.js
- /Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/loader-runner/lib/loadLoader.js
- /Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/webpack/lib/NormalModule.js
- /Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/webpack/lib/Compiler.js
- /Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/webpack/lib/webpack.js
- /Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/react-scripts/scripts/start.js (While processing: "/Users/c3050144/Documents/repos/icons/progress/react/demo/node_modules/babel-preset-react-app/dependencies.js")
```

**Comment by joebochill** [comment]
> Looks like the CI is not checking the react progress icon demo... I got this when I try to yarn start:react locally:

delete your node_modules folder and reinstall

**Review by huayunh — APPROVED** [review]

**Pull request merged**
