### PR TITLE
Feature/blui 2

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
-  Do the migration again, but this time on a mac.
-  Do the migration again, but this time don't delete the svg folder or the iconFont folder.

### CODE REVIEW

**Comment by jeffvg** [comment]
do we need to update svg>package.json here for this PR?

image

**Comment by jeffvg** [comment]
do we need to check-in the index.js for rn-vector? The build:rn-vector kicks this out

image

**Comment by emclaug2** [comment]
> do we need to check-in the index.js for rn-vector? The build:rn-vector kicks this out


I just ran `yarn build ` within the rn icons folder and that updated the index.js file.

**Comment by emclaug2** [comment]
> do we need to update svg>package.json here for this PR?

Yep, sorry this is updated now.

**Comment by jeffvg** [comment]
looks like one more here. MUI showcase > 
image

I might have something cached

**Comment by emclaug2** [comment]
> I might have something cached

Nope you're good; just pushed out a fix.  The demos shouldnt be converted but the eslintrc.js file was edited by accident.

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
